version: '3.8'


volumes:
  db:


services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - db:/var/lib/postgresql/data
      - ./.config/db/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'

  redis:
    image: redis:7.2.4
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  school-api:
    build:
      context: .
    container_name: school-api
    environment:
      - POSTGRES_HOST=db
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis